### ISSUE TITLE
Fix Public folder architecture

### ISSUE THREAD

**Issue by Nikazoid** [Nikazoid/medea#10]
We need to make the architecture of the folder more  "readable".
Below is some example of how it could look:

public/
-----users
-------user1
---------images

**Comment by martin-velikov** [comment]
I suggest a better structure:

public/
---images
-------[[entity]]

**Comment by Nikazoid** [comment]
Splendid, it will work.

**Comment by martin-velikov** [comment]
It's been done already in one of the previous commits.
